### ISSUE TITLE
Alert Screen bug on TranslationScreen

### ISSUE THREAD

**Issue by Ellaedrieth** [bsraayilmz/ce216Project#3]
### **_1) Steps to reproduce the bug:_**
a) Run the program.
b) Click on the Start button so that the app will move on to the ActionScreen.
c) Click on the Translation button so that the app will move on to the TranslationScreen.
d Write nothing into the translation bar.
e) Click the Find Translations button and then in VerifyScreen click on the Yes button, and then the error occurs.

### **_2) Expected Case:_**
In standard cases, the alert screen shouldn't be opened.

### **_3) What has happened?:_**
Program crashed.

### _**4) Some visual or text output:**_
![image](https://user-images.githubusercontent.com/93867521/230732143-6e4dd403-6a69-455b-bbaf-c35d27c81b3c.png)
![image](https://user-images.githubusercontent.com/93867521/230732191-cf6b356e-57ea-4fc2-9402-dd5646bd4542.png)

### **_5) Severity or priority of the error:_**
This error only occurs when nothing is written into the translation bar, so it is not severe.

**Comment by bsraayilmz** [comment]
By adjusting the conditions of the alert screen, the problem is the result. The program no longer crushes.

**Comment by bsraayilmz** [comment]
By adjusting the conditions of the alert screen, the problem is the result. The program no longer crushes.
