### ISSUE TITLE
Gradle Run (Compiling) Issue on Command Line / Terminal 

### ISSUE THREAD

**Issue by bsraayilmz** [bsraayilmz/ce216Project#4]
**_1) Steps to reproduce the bug:_**

a) Open the command line of your operating system. 
b) Write the commands below sequentially (the project path is assumed desktop and the operating system is assumed to be Windows. ): 
   -cd desktop
   -cd ce216Project-master
   -gradle build
   -gradle run

**_2) Expected Case:_**
In standard cases, Gradle should be able to compile the code, and the program should be opened on the screen. 

_**3) What has happened?:**_
The Command Line gave an error called 'Could not find or load main class com.team1.ce216project.HelloApplication'.

**_4)Some visual or text output:_**
![image](https://user-images.githubusercontent.com/99333733/235225709-c6e843e3-9778-4aad-b12d-cdf5d875f108.png)

**_5) Severity or priority of the error:_**
This error is crucial to be able to compile the offline dictionary.

**Comment by Ellaedrieth** [comment]
The problem has been solved with changing application dependency in the build.gradle file:
application {
    mainModule = 'com.team1.ce216project'
    mainClass = 'com.team1.ce216project.Main'
}
Main class path has been corrected as Main and the program is compiled and ran correctly through the command line.
